# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c4f500e1d29671d6e09116e91083ce94d2494fe69cb0a5546081f0ce534ab81aa1397747a866ac2686672fdba30a9426c0d819e63cc0ba03165f8a8794af66a

test:
  secret_key_base: a1c049327ee0bbfa2f084302eb9f7a0acf31d822bdad36ef53eb9597c0df0ddd79c732a65edaeb11b81afca36815dd083f7a4ea3ca46f2ca52e1cd3be15c9bae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
